/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsProjectIndexRouteImport } from './routes/projects.$project.index'
import { Route as ProjectsProjectFileRouteImport } from './routes/projects.$project.file'
import { Route as ProjectsProjectFilesRouteImport } from './routes/projects.$project.files'
import { Route as ProjectsProjectSearchRouteImport } from './routes/projects.$project.search'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIndexRoute = ProjectsProjectIndexRouteImport.update({
  id: '/projects/$project/',
  path: '/projects/$project/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectFileRoute = ProjectsProjectFileRouteImport.update({
  id: '/projects/$project/file',
  path: '/projects/$project/file',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectFilesRoute = ProjectsProjectFilesRouteImport.update({
  id: '/projects/$project/files',
  path: '/projects/$project/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectSearchRoute = ProjectsProjectSearchRouteImport.update({
  id: '/projects/$project/search',
  path: '/projects/$project/search',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/$project/file': typeof ProjectsProjectFileRoute
  '/projects/$project/files': typeof ProjectsProjectFilesRoute
  '/projects/$project/search': typeof ProjectsProjectSearchRoute
  '/projects/$project/': typeof ProjectsProjectIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/$project/file': typeof ProjectsProjectFileRoute
  '/projects/$project/files': typeof ProjectsProjectFilesRoute
  '/projects/$project/search': typeof ProjectsProjectSearchRoute
  '/projects/$project': typeof ProjectsProjectIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/$project/file': typeof ProjectsProjectFileRoute
  '/projects/$project/files': typeof ProjectsProjectFilesRoute
  '/projects/$project/search': typeof ProjectsProjectSearchRoute
  '/projects/$project/': typeof ProjectsProjectIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects/$project/file'
    | '/projects/$project/files'
    | '/projects/$project/search'
    | '/projects/$project/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects/$project/file'
    | '/projects/$project/files'
    | '/projects/$project/search'
    | '/projects/$project'
  id:
    | '__root__'
    | '/'
    | '/projects/$project/file'
    | '/projects/$project/files'
    | '/projects/$project/search'
    | '/projects/$project/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsProjectFileRoute: typeof ProjectsProjectFileRoute
  ProjectsProjectFilesRoute: typeof ProjectsProjectFilesRoute
  ProjectsProjectSearchRoute: typeof ProjectsProjectSearchRoute
  ProjectsProjectIndexRoute: typeof ProjectsProjectIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$project/': {
      id: '/projects/$project/'
      path: '/projects/$project'
      fullPath: '/projects/$project/'
      preLoaderRoute: typeof ProjectsProjectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$project/file': {
      id: '/projects/$project/file'
      path: '/projects/$project/file'
      fullPath: '/projects/$project/file'
      preLoaderRoute: typeof ProjectsProjectFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$project/files': {
      id: '/projects/$project/files'
      path: '/projects/$project/files'
      fullPath: '/projects/$project/files'
      preLoaderRoute: typeof ProjectsProjectFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$project/search': {
      id: '/projects/$project/search'
      path: '/projects/$project/search'
      fullPath: '/projects/$project/search'
      preLoaderRoute: typeof ProjectsProjectSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsProjectFileRoute: ProjectsProjectFileRoute,
  ProjectsProjectFilesRoute: ProjectsProjectFilesRoute,
  ProjectsProjectSearchRoute: ProjectsProjectSearchRoute,
  ProjectsProjectIndexRoute: ProjectsProjectIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
