/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as ProjectsProjectIndexRouteImport } from './routes/projects.$project.index'
import { Route as ProjectsProjectChurnRouteImport } from './routes/projects.$project.churn'
import { Route as ProjectsProjectCommitRouteImport } from './routes/projects.$project.commit'
import { Route as ProjectsProjectFileRouteImport } from './routes/projects.$project.file'
import { Route as ProjectsProjectFilesRouteImport } from './routes/projects.$project.files'
import { Route as ProjectsProjectHistoryRouteImport } from './routes/projects.$project.history'
import { Route as ProjectsProjectSearchRouteImport } from './routes/projects.$project.search'
import { Route as ProjectsProjectSettingsRouteImport } from './routes/projects.$project.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIndexRoute = ProjectsProjectIndexRouteImport.update({
  id: '/projects/$project/',
  path: '/projects/$project/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectChurnRoute = ProjectsProjectChurnRouteImport.update({
  id: '/projects/$project/churn',
  path: '/projects/$project/churn',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectCommitRoute = ProjectsProjectCommitRouteImport.update({
  id: '/projects/$project/commit',
  path: '/projects/$project/commit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectFileRoute = ProjectsProjectFileRouteImport.update({
  id: '/projects/$project/file',
  path: '/projects/$project/file',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectFilesRoute = ProjectsProjectFilesRouteImport.update({
  id: '/projects/$project/files',
  path: '/projects/$project/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectHistoryRoute = ProjectsProjectHistoryRouteImport.update({
  id: '/projects/$project/history',
  path: '/projects/$project/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectSearchRoute = ProjectsProjectSearchRouteImport.update({
  id: '/projects/$project/search',
  path: '/projects/$project/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectSettingsRoute = ProjectsProjectSettingsRouteImport.update({
  id: '/projects/$project/settings',
  path: '/projects/$project/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/new': typeof ProjectsNewRoute
  '/projects/$project/churn': typeof ProjectsProjectChurnRoute
  '/projects/$project/commit': typeof ProjectsProjectCommitRoute
  '/projects/$project/file': typeof ProjectsProjectFileRoute
  '/projects/$project/files': typeof ProjectsProjectFilesRoute
  '/projects/$project/history': typeof ProjectsProjectHistoryRoute
  '/projects/$project/search': typeof ProjectsProjectSearchRoute
  '/projects/$project/settings': typeof ProjectsProjectSettingsRoute
  '/projects/$project/': typeof ProjectsProjectIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/new': typeof ProjectsNewRoute
  '/projects/$project/churn': typeof ProjectsProjectChurnRoute
  '/projects/$project/commit': typeof ProjectsProjectCommitRoute
  '/projects/$project/file': typeof ProjectsProjectFileRoute
  '/projects/$project/files': typeof ProjectsProjectFilesRoute
  '/projects/$project/history': typeof ProjectsProjectHistoryRoute
  '/projects/$project/search': typeof ProjectsProjectSearchRoute
  '/projects/$project/settings': typeof ProjectsProjectSettingsRoute
  '/projects/$project': typeof ProjectsProjectIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/new': typeof ProjectsNewRoute
  '/projects/$project/churn': typeof ProjectsProjectChurnRoute
  '/projects/$project/commit': typeof ProjectsProjectCommitRoute
  '/projects/$project/file': typeof ProjectsProjectFileRoute
  '/projects/$project/files': typeof ProjectsProjectFilesRoute
  '/projects/$project/history': typeof ProjectsProjectHistoryRoute
  '/projects/$project/search': typeof ProjectsProjectSearchRoute
  '/projects/$project/settings': typeof ProjectsProjectSettingsRoute
  '/projects/$project/': typeof ProjectsProjectIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects/new'
    | '/projects/$project/churn'
    | '/projects/$project/commit'
    | '/projects/$project/file'
    | '/projects/$project/files'
    | '/projects/$project/history'
    | '/projects/$project/search'
    | '/projects/$project/settings'
    | '/projects/$project/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects/new'
    | '/projects/$project/churn'
    | '/projects/$project/commit'
    | '/projects/$project/file'
    | '/projects/$project/files'
    | '/projects/$project/history'
    | '/projects/$project/search'
    | '/projects/$project/settings'
    | '/projects/$project'
  id:
    | '__root__'
    | '/'
    | '/projects/new'
    | '/projects/$project/churn'
    | '/projects/$project/commit'
    | '/projects/$project/file'
    | '/projects/$project/files'
    | '/projects/$project/history'
    | '/projects/$project/search'
    | '/projects/$project/settings'
    | '/projects/$project/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
  ProjectsProjectChurnRoute: typeof ProjectsProjectChurnRoute
  ProjectsProjectCommitRoute: typeof ProjectsProjectCommitRoute
  ProjectsProjectFileRoute: typeof ProjectsProjectFileRoute
  ProjectsProjectFilesRoute: typeof ProjectsProjectFilesRoute
  ProjectsProjectHistoryRoute: typeof ProjectsProjectHistoryRoute
  ProjectsProjectSearchRoute: typeof ProjectsProjectSearchRoute
  ProjectsProjectSettingsRoute: typeof ProjectsProjectSettingsRoute
  ProjectsProjectIndexRoute: typeof ProjectsProjectIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$project/': {
      id: '/projects/$project/'
      path: '/projects/$project'
      fullPath: '/projects/$project/'
      preLoaderRoute: typeof ProjectsProjectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$project/churn': {
      id: '/projects/$project/churn'
      path: '/projects/$project/churn'
      fullPath: '/projects/$project/churn'
      preLoaderRoute: typeof ProjectsProjectChurnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$project/commit': {
      id: '/projects/$project/commit'
      path: '/projects/$project/commit'
      fullPath: '/projects/$project/commit'
      preLoaderRoute: typeof ProjectsProjectCommitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$project/file': {
      id: '/projects/$project/file'
      path: '/projects/$project/file'
      fullPath: '/projects/$project/file'
      preLoaderRoute: typeof ProjectsProjectFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$project/files': {
      id: '/projects/$project/files'
      path: '/projects/$project/files'
      fullPath: '/projects/$project/files'
      preLoaderRoute: typeof ProjectsProjectFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$project/history': {
      id: '/projects/$project/history'
      path: '/projects/$project/history'
      fullPath: '/projects/$project/history'
      preLoaderRoute: typeof ProjectsProjectHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$project/search': {
      id: '/projects/$project/search'
      path: '/projects/$project/search'
      fullPath: '/projects/$project/search'
      preLoaderRoute: typeof ProjectsProjectSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$project/settings': {
      id: '/projects/$project/settings'
      path: '/projects/$project/settings'
      fullPath: '/projects/$project/settings'
      preLoaderRoute: typeof ProjectsProjectSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsNewRoute: ProjectsNewRoute,
  ProjectsProjectChurnRoute: ProjectsProjectChurnRoute,
  ProjectsProjectCommitRoute: ProjectsProjectCommitRoute,
  ProjectsProjectFileRoute: ProjectsProjectFileRoute,
  ProjectsProjectFilesRoute: ProjectsProjectFilesRoute,
  ProjectsProjectHistoryRoute: ProjectsProjectHistoryRoute,
  ProjectsProjectSearchRoute: ProjectsProjectSearchRoute,
  ProjectsProjectSettingsRoute: ProjectsProjectSettingsRoute,
  ProjectsProjectIndexRoute: ProjectsProjectIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
